=== bristermitten/hot-takes/hotTakeData.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Hot Take Data",
  "description": "A collection of data for generating programming hot takes.",
  "type": "object",
  "properties": {
    "people": {
      "description": "A list of influential people in the tech industry.",
      "type": "array",
      "items": { "$ref": "#/$defs/takeItem" }
    },
    "companies": {
      "description": "A list of tech companies.",
      "type": "array",
      "items": { "$ref": "#/$defs/takeItem" }
    },
    "languages": {
      "description": "A list of programming languages.",
      "type": "array",
      "items": { "$ref": "#/$defs/takeItem" }
    },
    "technologies": {
      "description": "A list of various technologies, frameworks, and concepts.",
      "type": "array",
      "items": { "$ref": "#/$defs/takeItem" }
    },
    "problems": {
      "description": "A list of common problems and concepts in software development.",
      "type": "array",
      "items": { "type": "string" }
    },
    "tlds": {
      "description": "A list of top-level domains.",
      "type": "array",
      "items": { "type": "string" }
    },
    "takes": {
      "description": "A list of hot take templates.",
      "type": "array",
      "items": { "$ref": "#/$defs/takeDefinition" }
    }
  },
  "required": [
    "people",
    "companies",
    "languages",
    "technologies",
    "problems",
    "tlds",
    "takes"
  ],
  "$defs": {
    "takeObject": {
      "type": "object",
      "description": "A take object representing an item with text and an associated image.",
      "properties": {
        "take": {
          "description": "The text.",
          "type": "string"
        },
        "image": {
          "description": "The path to the image for the item.",
          "type": "string",
          "format": "uri-relative"
        }
      },
      "required": ["take", "image"]
    },
    "takeItem": {
      "description": "Either a standalone take or a take object",
      "oneOf": [{ "type": "string" }, { "$ref": "#/$defs/takeObject" }]
    },
    "takeDefinitionObject": {
      "type": "object",
      "properties": {
        "take": {
          "description": "The hot take template string.",
          "type": "string"
        },
        "image": {
          "description": "The path to an image (or images) associated with the take.",
          "oneOf": [
            {
              "type": "string",
              "format": "uri-relative"
            },
            {
              "type": "array",
              "items": {
                "type": "string",
                "format": "uri-relative"
              }
            }
          ]
        }
      },
      "required": ["take"]
    },
    "takeDefinition": {
      "description": "Either a simple take template string or a template object with an image.",
      "oneOf": [
        { "type": "string" },
        { "$ref": "#/$defs/takeDefinitionObject" }
      ]
    }
  }
}

=== bristermitten/hot-takes/hotTakeData.json
{
  "people": [
    {
      "take": "Linus Torvalds",
      "image": "./img/linus torvalds.webp"
    },
    {
      "take": "Terry Davis",
      "image": "./img/terry davis.jpg"
    },
    {
      "take": "Simon Peyton-Jones",
      "image": "./img/simon peyton-jones.jpg"
    },
    {
      "take": "James Gosling",
      "image": "./img/james gosling.jpg"
    },
    {
      "take": "Anders Hejlsberg",
      "image": "./img/anders hejlsberg.jpg"
    },
    {
      "take": "Bjarne Stroustrup",
      "image": "./img/bjarne stroustrup.jpg"
    },
    {
      "take": "Ken Thompson",
      "image": "./img/ken thompson.jpg"
    },
    {
      "take": "Grace Hopper",
      "image": "./img/grace hopper.webp"
    },
    {
      "take": "Robert C. Martin",
      "image": "./img/robert c martin.jpg"
    },
    {
      "take": "Guido van Rossum",
      "image": "./img/guido van rossum.jpg"
    },
    {
      "take": "Alan Turing",
      "image": "./img/alan turing.jpg"
    },
    {
      "take": "Alonzo Church",
      "image": "./img/alonzo church.jpeg"
    },
    {
      "take": "Graydon Hoare",
      "image": "./img/graydon hoare.webp"
    },
    {
      "take": "Dennis Ritchie",
      "image": "./img/dennis ritchie.webp"
    },
    {
      "take": "Rich Hickey",
      "image": "./img/rich hickey.jpeg"
    },
    {
      "take": "Rasmus Lerdorf",
      "image": "./img/rasmus lerdorf.jpg"
    },
    {
      "take": "Richard Stallman",
      "image": "./img/richard stallman.jpg"
    },
    {
      "take": "Mark Zuckerberg",
      "image": "./img/mark zuckerberg.jpg"
    },
    {
      "take": "@elonmusk",
      "image": "./img/elon musk.webp"
    },
    {
      "take": "Don Syme",
      "image": "./img/don syme.webp"
    },
    {
      "take": "@jeffbezos",
      "image": "./img/jeff bezos.jpg"
    },
    {
      "take": "@tim_cook",
      "image": "./img/tim cook.jpg"
    },
    {
      "take": "Ajit Pai",
      "image": "./img/ajit pai.jpg"
    },
    {
      "take": "@jack",
      "image": "./img/jack dorsey.webp"
    },
    {
      "take": "Susan Wojcicki",
      "image": "./img/susan wojcicki.jpg"
    },
    {
      "take": "@BillGates",
      "image": "./img/bill gates.jpg"
    },
    {
      "take": "Steve Jobs",
      "image": "./img/steve jobs.jpg"
    },
    {
      "take": "Kevin Mitnick",
      "image": "./img/kevin mitnick.webp"
    },
    {
      "take": "Troy Hunt",
      "image": "./img/troy hunt.jpg"
    },
    {
      "take": "Euclid of Alexandria",
      "image": "./img/euclid.webp"
    },
    {
      "take": "Ada Lovelace",
      "image": "./img/ada lovelace.webp"
    },
    {
      "take": "Charles Babbage",
      "image": "./img/charles babbage.webp"
    },
    {
      "take": "Tom Scott",
      "image": "./img/tom scott.jpg"
    },
    {
      "take": "Barbara Liskov",
      "image": "./img/barbara liskov.jpg"
    },
    {
      "take": "John von Neumann",
      "image": "./img/john von neumann.gif"
    },
    {
      "take": "Kathleen Booth",
      "image": "./img/kathleen booth.jpg"
    },
    {
      "take": "Edsger Dijkstra",
      "image": "./img/edsger dijkstra.jpg"
    }
  ],
  "companies": [
    {
      "take": "@Jetbrains",
      "image": "./img/jetbrains.webp"
    },
    {
      "take": "Apache",
      "image": "./img/apache.png"
    },
    {
      "take": "@google",
      "image": "./img/google.png"
    },
    {
      "take": "@microsoft",
      "image": "./img/microsoft.png"
    },
    {
      "take": "@apple",
      "image": "./img/apple.png"
    },
    {
      "take": "@Oracle",
      "image": "./img/oracle.png"
    },
    {
      "take": "@IBM",
      "image": "./img/ibm.png"
    },
    {
      "take": "@Meta",
      "image": "./img/meta.png"
    },
    {
      "take": "@Amazon",
      "image": "./img/amazon.png"
    },
    {
      "take": "@Intel",
      "image": "./img/intel.png"
    },
    {
      "take": "@Adobe",
      "image": "./img/adobe.png"
    },
    {
      "take": "@AMD",
      "image": "./img/amd.png"
    },
    {
      "take": "@Nvidia",
      "image": "./img/nvidia.png"
    },
    {
      "take": "@Mozilla",
      "image": "./img/mozilla.jpg"
    },
    {
      "take": "Free Software Foundation",
      "image": "./img/free software foundation.png"
    },
    {
      "take": "GNU",
      "image": "./img/gnu.png"
    },
    {
      "take": "Tencent",
      "image": "./img/tencent.png"
    },
    {
      "take": "Alibaba",
      "image": "./img/alibaba.png"
    },
    {
      "take": "Baidu",
      "image": "./img/baidu.png"
    },
    {
      "take": "@Samsung",
      "image": "./img/samsung.png"
    },
    {
      "take": "@Sony",
      "image": "./img/sony.png"
    },
    {
      "take": "@Cisco",
      "image": "./img/cisco.png"
    },
    {
      "take": "@OVH",
      "image": "./img/ovh.png"
    },
    {
      "take": "@Scaleway",
      "image": "./img/scaleway.webp"
    },
    {
      "take": "@Vultr",
      "image": "./img/vultr.webp"
    },
    {
      "take": "@Hetzner",
      "image": "./img/hetzner.png"
    },
    {
      "take": "@Linode",
      "image": "./img/linode.png"
    },
    {
      "take": "@Cloudflare",
      "image": "./img/cloudflare.png"
    },
    {
      "take": "@ARM",
      "image": "./img/arm.png"
    },
    {
      "take": "@Tesla",
      "image": "./img/tesla.png"
    },
    {
      "take": "@SpaceX",
      "image": "./img/spacex.jpg"
    },
    {
      "take": "@NASA",
      "image": "./img/nasa.png"
    },
    {
      "take": "Mojang",
      "image": "./img/mojang.png"
    },
    {
      "take": "Spigot",
      "image": "./img/spigot.png"
    },
    {
      "take": "Bukkit",
      "image": "./img/bukkit.png"
    },
    {
      "take": "@Patreon",
      "image": "./img/patreon.png"
    },
    {
      "take": "@PayPal",
      "image": "./img/paypal.png"
    },
    {
      "take": "@OpenAI",
      "image": "./img/openai.png"
    }
  ],
  "languages": [
    {
      "take": "#Solidity",
      "image": "./img/solidity.png"
    },
    {
      "take": "#C",
      "image": "./img/c.png"
    },
    {
      "take": "C++",
      "image": "./img/c++.png"
    },
    {
      "take": "Carbon",
      "image": "./img/carbon.png"
    },
    {
      "take": "D",
      "image": "./img/d.png"
    },
    {
      "take": "C#",
      "image": "./img/csharp.png"
    },
    {
      "take": "F#",
      "image": "./img/fsharp.png"
    },
    {
      "take": "#OCaml",
      "image": "./img/ocaml.png"
    },
    {
      "take": "#Haskell",
      "image": "./img/haskell.png"
    },
    {
      "take": "#Prolog",
      "image": "./img/prolog.png"
    },
    {
      "take": "#Elm",
      "image": "./img/elm.png"
    },
    {
      "take": "#Elixir",
      "image": "./img/elixir.png"
    },
    {
      "take": "#Erlang",
      "image": "./img/erlang.png"
    },
    {
      "take": "#Clojure",
      "image": "./img/clojure.png"
    },
    {
      "take": "#Java",
      "image": "./img/java.png"
    },
    {
      "take": "#Scala",
      "image": "./img/scala.png"
    },
    {
      "take": "#Groovy",
      "image": "./img/groovy.png"
    },
    {
      "take": "#Kotlin",
      "image": "./img/kotlin.png"
    },
    {
      "take": "#Swift",
      "image": "./img/swift.png"
    },
    {
      "take": "#JavaScript",
      "image": "./img/javascript.png"
    },
    {
      "take": "#CoffeeScript",
      "image": "./img/coffeescript.png"
    },
    {
      "take": "#TypeScript",
      "image": "./img/typescript.png"
    },
    {
      "take": "#PHP",
      "image": "./img/php.png"
    },
    {
      "take": "#Python",
      "image": "./img/python.png"
    },
    {
      "take": "#Go",
      "image": "./img/go.png"
    },
    {
      "take": "#Rust",
      "image": "./img/rust.png"
    },
    {
      "take": "#VLang",
      "image": "./img/v.png"
    },
    {
      "take": "#Ruby",
      "image": "./img/ruby.png"
    },
    {
      "take": "#Crystal",
      "image": "./img/crystal.png"
    },
    {
      "take": "#Lua",
      "image": "./img/lua.png"
    },
    {
      "take": "R",
      "image": "./img/r.jpeg"
    },
    {
      "take": "#MATLAB",
      "image": "./img/matlab.png"
    },
    {
      "take": "#Wolfram",
      "image": "./img/wolfram.png"
    },
    {
      "take": "#Dart",
      "image": "./img/dart.png"
    },
    {
      "take": "#Julia",
      "image": "./img/julia.png"
    },
    {
      "take": "#Perl",
      "image": "./img/perl.png"
    },
    {
      "take": "APL",
      "image": "./img/apl.png"
    },
    {
      "take": "BQN",
      "image": "./img/bqn.png"
    },
    {
      "take": "Brainf**k",
      "image": "./img/brainfuck.png"
    },
    {
      "take": "#COBOL",
      "image": "./img/cobol.webp"
    },
    {
      "take": "#Fortran",
      "image": "./img/fortran.png"
    },
    {
      "take": "ALGOL 55",
      "image": "./img/algol.webp"
    },
    {
      "take": "ALGOL 60",
      "image": "./img/algol.webp"
    },
    {
      "take": "ALGOL 68",
      "image": "./img/algol.webp"
    },
    {
      "take": "Assembly",
      "image": "./img/assembly.png"
    },
    {
      "take": "#ZSH",
      "image": "./img/zsh.png"
    },
    {
      "take": "#Bash",
      "image": "./img/bash.png"
    },
    {
      "take": "#PowerShell",
      "image": "./img/powershell.png"
    },
    {
      "take": "Scratch",
      "image": "./img/scratch.png"
    },
    {
      "take": "#HTML",
      "image": "./img/html.png"
    },
    {
      "take": "#CSS",
      "image": "./img/css.png"
    },
    {
      "take": "#SASS",
      "image": "./img/sass.png"
    },
    {
      "take": "#LESS",
      "image": "./img/less.png"
    },
    {
      "take": "#Angular",
      "image": "./img/angular.png"
    },
    {
      "take": "#React",
      "image": "./img/react.png"
    },
    {
      "take": "#Vue",
      "image": "./img/vue.png"
    },
    "Malbolge",
    {
      "take": "Verilog",
      "image": "./img/verilog.png"
    }
  ],
  "technologies": [
    {
